apiVersion: v1
kind: Secret
metadata:
    name: forward-auth
stringData:
    secret: ENC[AES256_GCM,data:O3zlMIby1Q==,iv:2t0lFJOMI7q1qR2bF9ECYLynhmQ6tF+08jdbv+3eFBI=,tag:nIQQdZbLilLiYATzVgmztw==,type:str]
    oauth-client-secret: ENC[AES256_GCM,data:QE8s7FkAyA==,iv:D7CS1FnnbovCRtPBtBODyDQR2ScseKGuyWwpEOaajvA=,tag:xmCOLQGOa6ub610b2M6mww==,type:str]
sops:
    age:
        - recipient: age1wjup22frscewff097e978zagculhmyx9pnlmlhqzj3pjd4277spq5pcjka
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOVklmNStYeVk1WlY3Mmxq
            NHQ5c21UTXM3dEpiYkVtQTRaRnJaN003ZUQ0CkFlN0FXNFhEUXNqTnBtaWhHdFhJ
            cXVBV2xwb0tDN0Y4NG0vOWE5QVBtVUkKLS0tIEswZ3RSTVJJVkdrUHpqNmhIZkNq
            YStDM0FLREt1Ni9kNzNTR0paOGZib2cKcG3JTuW5nmIF5MuDw6ikGY19m9V3bvey
            HSAvRQOdjG3uAsZloWhKGniATZmCzvX9knNAEc/9h5qAgtiboifNDA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-03T04:17:40Z"
    mac: ENC[AES256_GCM,data:07W6HJinjNGpQ2pUHa5MJC/DmrWG8slChRI15yFzRcHCHbAptNFaYbKFLClQbXY1ARtfpJUedJ+fTt3ylHUOkw9MnonGpMyatsbAKPE7kTg0IROmTjMP9pJyssExw1QowSPWqVwpXDlHyg+4DTZL1+vSLIjT59RI5ASKyGsISzI=,iv:lgh0Ia9eBBLreTdqGJbmkNAq97Cb4Z9nHP9LvubwlIk=,tag:qubbPEWHkDcYKBmi3upucA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.10.2
