{{- range $group, $_ := $.Values.groups }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ $.Release.Name }}-header-group-{{ $group }}
  namespace: {{ $.Release.Namespace }}

spec:
  headers:
    customRequestHeaders:
      X-Forward-Auth-Group: {{ $group }}

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ $.Release.Name }}-group-{{ $group }}
  namespace: {{ $.Release.Namespace }}

spec:
  chain:
    middlewares:
      - name: {{ $.Release.Name }}-header-group-{{ $group }}
      - name: {{ $.Release.Name }}-core

{{- end }}
