apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana

spec:
  entryPoints:
    - web

  routes:
    - kind: Rule
      match: Host(`monitor.example.com`)
      middlewares:
        - name: auth-group-admin
          namespace: auth
      services:
        - kind: Service
          name: grafana
          port: 80
          scheme: http

    - kind: Rule
      match: Host(`alertmanager.example.com`)
      middlewares:
        - name: auth-group-admin
          namespace: auth
      services:
        - kind: Service
          name: vmalertmanager-vms-victoria-metrics-k8s-stack
          port: http
          scheme: http
