{
 "title": "Cluster / OpenCost",
 "tags": [ "cluster-mixin" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_labels, namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster Wide", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster Cost",
   "type": "stat",
   "description": "Cluster cost of current range\n\nCluster cost = Node cost + PV cost + Overhead (cluster+LB) cost",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum_over_time(sum_node_total_hourly_cost[$__range:$__rate_interval]) / (1h / $__rate_interval)\n+\nsum(sum_over_time(\n    (\n        sum by (persistentvolume) (pv_hourly_cost)\n        * sum by (persistentvolume) (kube_persistentvolume_capacity_bytes / 1024 / 1024 / 1024)\n    )[$__range:$__rate_interval]\n)) / (1h / $__rate_interval)\n+\nsum_over_time(\n    (sum(kubecost_load_balancer_cost OR on() vector(0)) + (sum(kubecost_cluster_management_cost > 0) or vector(0.1)))[$__range:$__rate_interval]\n) / (1h / $__rate_interval)",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Workload Cost",
   "type": "stat",
   "gridPos": { "h": 11, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum_over_time(sum_node_total_hourly_cost[$__range:$__rate_interval]) / (1h / $__rate_interval)",
     "legendFormat": "workload"
    }
   ]
  },
  {
   "title": "Workload Cost (by namespace)",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(\r\n    ((namespace_cpu_cost + namespace_memory_cost) OR on (namespace) sum by (namespace) (kube_namespace_labels) * 0) [$__range:$__rate_interval]) / (1h / $__rate_interval)",
     "legendFormat": "{{ namespace }}"
    },
    {
     "expr": "sum_over_time(sum_node_total_hourly_cost[$__range:$__rate_interval]) / (1h / $__rate_interval)\n-\nsum(sum_over_time(\n    ((namespace_cpu_cost + namespace_memory_cost) OR on (namespace) sum by (namespace) (kube_namespace_labels) * 0) [$__range:$__rate_interval]) / (1h / $__rate_interval))",
     "legendFormat": "idle"
    }
   ]
  },
  {
   "title": "Cluster Cost",
   "type": "piechart",
   "description": "Cluster cost of current range\n\nCluster cost = Node cost + PV cost + Overhead (cluster+LB) cost",
   "gridPos": { "h": 27, "w": 9, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum_over_time(sum_node_total_hourly_cost[$__range:$__rate_interval]) / (1h / $__rate_interval)",
     "legendFormat": "workload"
    },
    {
     "expr": "sum(sum_over_time(\n    (\n        sum by (persistentvolume) (pv_hourly_cost)\n        * sum by (persistentvolume) (kube_persistentvolume_capacity_bytes / 1024 / 1024 / 1024)\n    )[$__range:$__rate_interval]\n)) / (1h / $__rate_interval)",
     "legendFormat": "pv"
    },
    {
     "expr": "sum_over_time(\n    (sum(kubecost_load_balancer_cost OR on() vector(0)) + (sum(kubecost_cluster_management_cost > 0) or vector(0.1)))[$__range:$__rate_interval]\n) / (1h / $__rate_interval)",
     "legendFormat": "overhead"
    }
   ]
  },
  {
   "title": "PV Cost",
   "type": "stat",
   "gridPos": { "h": 11, "w": 3, "x": 9, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum(sum_over_time(\n    (\n        sum by (persistentvolume) (pv_hourly_cost)\n        * sum by (persistentvolume) (kube_persistentvolume_capacity_bytes / 1024 / 1024 / 1024)\n    )[$__range:$__rate_interval]\n)) / (1h / $__rate_interval)",
     "legendFormat": "pv"
    }
   ]
  },
  {
   "title": "PV Cost (by namespace)",
   "type": "piechart",
   "description": "PersistentVolume cost of current range",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (namespace) (\n    sum_over_time((\n        sum by (persistentvolume) (pv_hourly_cost)\n        * on (persistentvolume) group_right() sum by (persistentvolume, namespace) (pod_pvc_allocation / 1024 / 1024 / 1024)\n    )[$__range:$__rate_interval])\n) / (1h / $__rate_interval)",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Overhead Cost",
   "type": "stat",
   "gridPos": { "h": 11, "w": 3, "x": 9, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum_over_time(\n    (sum(kubecost_load_balancer_cost OR on() vector(0)) + (sum(kubecost_cluster_management_cost > 0) or vector(0.1)))[$__range:$__rate_interval]\n) / (1h / $__rate_interval)",
     "legendFormat": "overhead"
    }
   ]
  },
  {
   "title": "Overhead Cost",
   "type": "piechart",
   "description": "Overhead (cluster+LB) cost of current range",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(\n    sum(kubecost_load_balancer_cost OR on() vector(0))[$__range:$__rate_interval]\n) / (1h / $__rate_interval)",
     "legendFormat": "lb"
    },
    {
     "expr": "sum_over_time(\n    (sum(kubecost_cluster_management_cost > 0) or vector(0.1))[$__range:$__rate_interval]\n) / (1h / $__rate_interval)",
     "legendFormat": "cluster"
    }
   ]
  },
  { "title": "Workload", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Hourly Workload Cost (by node)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum by (node) (node_total_hourly_cost{node!~\"fargate.*\"})",
     "legendFormat": "{{ node }}"
    },
    {
     "expr": "sum by (node) (container_cpu_allocation{node=~\"fargate.*\"}) * on(node) group_left() (avg by (node) (node_cpu_hourly_cost))\n+\nsum by (node) (container_memory_allocation_bytes{node=~\"fargate.*\"} / 1024 / 1024 / 1024 + 0.25) * on(node) group_left() (avg by (node) (node_ram_hourly_cost))",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Hourly Workload Cost (by namespace)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    { "expr": "sum_node_total_hourly_cost", "legendFormat": "Total" },
    {
     "expr": "namespace_cpu_cost + namespace_memory_cost",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Hourly Workload Cost (by container)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum by (namespace, container) (\n\tsum by (container,namespace, instance) (container_memory_allocation_bytes  / 1024 / 1024 / 1024)\n\t* on (instance) group_left() (avg by (instance) (node_ram_hourly_cost))\n  + sum by (container, namespace, instance) (container_cpu_allocation)\n\t* on (instance) group_left() (avg by (instance) (node_cpu_hourly_cost))\n)",
     "legendFormat": "{{namespace}} / {{container}}"
    }
   ]
  },
  { "title": "Namespace ($namespace)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Workload Cost",
   "type": "piechart",
   "description": "Workload cost of current range",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(sum by (container) (\n    sum by (container, instance) (container_memory_allocation_bytes{namespace=\"$namespace\"})\n    * on(instance) group_left() (\n        node_ram_hourly_cost{} / 1024 / 1024 / 1024\n        + on(node,instance_type) group_left()\n            avg by (node, instance_type) (\n            label_replace\n            (\n                kube_node_labels{}, \"instance_type\", \"$1\", \"label_node_kubernetes_io_instance_type\", \"(.*)\"\n            ) * 0\n            )\n    )\n    + \n    sum by (container, instance) (container_cpu_allocation{namespace=\"$namespace\"})\n    * on(instance) group_left() (\n        node_cpu_hourly_cost{}\n        + on(node,instance_type) group_left()\n            avg by (node, instance_type) (\n            label_replace (\n                kube_node_labels{}, \"instance_type\", \"$1\", \"label_node_kubernetes_io_instance_type\", \"(.*)\"\n            ) * 0\n            )\n    )\n)[$__range:$__rate_interval]) / (1h / $__rate_interval)",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "PV Cost by Pod",
   "type": "piechart",
   "description": "PersistentVolume cost of current range",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pod) (\n    sum_over_time((\n        sum by (persistentvolume) (pv_hourly_cost)\n        * on (persistentvolume) group_right() sum by (persistentvolume, pod) (pod_pvc_allocation{namespace=\"$namespace\"} / 1024 / 1024 / 1024)\n    )[$__range:$__rate_interval]) / (1h / $__rate_interval)\n)",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "Hourly Workload Cost by Container",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum by (namespace, container) (\n\tsum by (container,namespace, instance) (container_memory_allocation_bytes{namespace=\"$namespace\"} / 1024 / 1024 / 1024)\n\t* on (instance) group_left() (\n\t\tnode_ram_hourly_cost{}\n\t\t# + on(node,instance_type) group_left()\n\t\t# label_replace(\n\t\t# \tkube_node_labels{}, \"instance_type\", \"$1\", \"label_node_kubernetes_io_instance_type\", \"(.*)\"\n\t\t# ) * 0\n\t)\n  + sum by (container, namespace, instance) (container_cpu_allocation{namespace=\"$namespace\"})\n\t* on (instance) group_left() (\n\t\tnode_cpu_hourly_cost{}\n\t\t# + on(node, instance_type) group_left()\n\t\t# label_replace(\n\t\t# \tkube_node_labels{}, \"instance_type\", \"$1\", \"label_node_kubernetes_io_instance_type\", \"(.*)\"\n\t\t# ) * 0\n\t)\n)",
     "legendFormat": "{{namespace}} / {{container}}"
    }
   ]
  }
 ]
}