{
 "title": "Cluster / Traefik",
 "tags": [
  "traefik",
  "cluster-mixin"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "group_by", "query": "namespace, service" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(traefik_service_requests_total,service)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(traefik_service_requests_total{service=~\"$namespace-.+\"},service)"
    }
   },
   {
    "name": "slow_threshold",
    "query": "0.1s : 0.1, 0.3s : 0.3, 1.2s : 1.2, 5s : 5"
   }
  ]
 },
 "panels": [
  { "title": "Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{service=~\"$namespace-.+\", service=~\"$service\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Apdex Score",
   "type": "stat",
   "description": "Satisfactory: not 5xx and <=0.3s,\nTolerable: not 5xx and <=1.2s\n\nhttps://medium.com/@tristan_96324/prometheus-apdex-alerting-d17a065e39d0",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(\r\n    sum(increase(\r\n        label_replace(\r\n            traefik_service_request_duration_seconds_bucket{service=~\"$namespace-.+\", service=~\"$service\", code!~\"5..\", le=\"0.3\"}\r\n        , \"namespace\", \"$1\", \"service\", \"([a-z]+)-.+\")\r\n    [$__range]))\r\n    +\r\n    sum(increase(\r\n        label_replace(\r\n            traefik_service_request_duration_seconds_bucket{service=~\"$namespace-.+\", service=~\"$service\", code!~\"5xx\", le=\"1.2\"}\r\n        , \"namespace\", \"$1\", \"service\", \"([a-z]+)-.+\")\r\n    [$__range]))\r\n) / 2\r\n/ \r\nsum(increase(\r\n    label_replace(\r\n        traefik_service_request_duration_seconds_bucket{service=~\"$namespace-.+\", service=~\"$service\", le=\"+Inf\"}\r\n    , \"namespace\", \"$1\", \"service\", \"([a-z]+)-.+\")\r\n[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Success (non-5xx) Rate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{service=~\"$namespace-.+\", service=~\"$service\", code!~\"5..\"}[$__range]))\r\n/\r\nsum(increase(traefik_service_requests_total{service=~\"$namespace-.+\", service=~\"$service\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Slow Requests (>=$slow_threshold)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(\r\nsum(increase(traefik_service_request_duration_seconds_bucket{service=~\"$namespace-.+\", service=~\"$service\", le=\"+Inf\"}[$__range]))\r\n-\r\nsum(increase(traefik_service_request_duration_seconds_bucket{service=~\"$namespace-.+\", service=~\"$service\", le=\"$slow_threshold\"}[$__range]))\r\n)\r\n/\r\nsum(increase(traefik_service_request_duration_seconds_bucket{service=~\"$namespace-.+\", service=~\"$service\", le=\"+Inf\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed (5xx) Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "req" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{service=~\"$namespace-.+\", service=~\"$service\", code=~\"5..\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Slow Requests (>=$slow_threshold)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "req" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(traefik_service_request_duration_seconds_bucket{service=~\"$namespace-.+\", service=~\"$service\", le=\"+Inf\"}[$__range]))\r\n-\r\nsum(increase(traefik_service_request_duration_seconds_bucket{service=~\"$namespace-.+\", service=~\"$service\", le=\"$slow_threshold\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Apdex Score",
   "type": "timeseries",
   "description": "Satisfactory: not 5xx and <=0.3s,\nTolerable: not 5xx and <=1.2s\n\nhttps://medium.com/@tristan_96324/prometheus-apdex-alerting-d17a065e39d0",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "(\r\n    sum by ($group_by) (increase(\r\n        label_replace(\r\n            traefik_service_request_duration_seconds_bucket{service=~\"$namespace-.+\", service=~\"$service\", code!~\"5..\", le=\"0.3\"}\r\n        , \"namespace\", \"$1\", \"service\", \"([a-z]+)-.+\")\r\n    [$__rate_interval]))\r\n    +\r\n    sum by ($group_by) (increase(\r\n        label_replace(\r\n            traefik_service_request_duration_seconds_bucket{service=~\"$namespace-.+\", service=~\"$service\", code!~\"5..\", le=\"1.2\"}\r\n        , \"namespace\", \"$1\", \"service\", \"([a-z]+)-.+\")\r\n    [$__rate_interval]))\r\n) / 2\r\n/ \r\nsum by ($group_by) (increase(\r\n    label_replace(\r\n        traefik_service_request_duration_seconds_bucket{service=~\"$namespace-.+\", service=~\"$service\", le=\"+Inf\"}\r\n    , \"namespace\", \"$1\", \"service\", \"([a-z]+)-.+\")\r\n[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by ($group_by) (\r\n    label_replace(\r\n        rate(\r\n          traefik_service_requests_total{service=~\"$namespace-.+\", service=~\"$service\"}\r\n      [$__rate_interval])\r\n    , \"namespace\", \"$1\", \"service\", \"^([a-z]+)-.+\")\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "p99 Latency (estimation)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, $group_by) (rate(\r\n    label_replace(\r\n    traefik_service_request_duration_seconds_bucket{service=~\"$namespace-.+\", service=~\"$service\"}\r\n    , \"namespace\", \"$1\", \"service\", \"([a-z]+)-.+\")\r\n[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "sum by (le) (increase(\r\n    traefik_service_request_duration_seconds_bucket{service=~\"$namespace-.+\", service=~\"$service\"}\r\n[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Slow Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\nsum(increase(traefik_service_request_duration_seconds_bucket{service=~\"$namespace-.+\", service=~\"$service\", le=\"+Inf\"}[$__rate_interval]))\n-\nsum by (le) (increase(traefik_service_request_duration_seconds_bucket{service=~\"$namespace-.+\", service=~\"$service\", le!=\"+Inf\"}[$__rate_interval]))\n)\n/\nsum(increase(traefik_service_request_duration_seconds_bucket{service=~\"$namespace-.+\", service=~\"$service\", le=\"+Inf\"}[$__rate_interval]))",
     "legendFormat": ">={{ le }}s"
    }
   ]
  },
  {
   "title": "Slow Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "req/s" } },
   "targets": [
    {
     "expr": "(\nsum(rate(traefik_service_request_duration_seconds_bucket{service=~\"$namespace-.+\", service=~\"$service\", le=\"+Inf\"}[$__rate_interval]))\n-\nsum by (le) (rate(traefik_service_request_duration_seconds_bucket{service=~\"$namespace-.+\", service=~\"$service\", le!=\"+Inf\"}[$__rate_interval]))\n)",
     "legendFormat": ">={{ le }}s"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Failed (5xx) Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by ($group_by) (\r\n    label_replace(\r\n        rate(\r\n          traefik_service_requests_total{service=~\"$namespace-.+\", service=~\"$service\", code=~\"5..\"}\r\n      [$__rate_interval])\r\n    , \"namespace\", \"$1\", \"service\", \"^([a-z]+)-.+\")\r\n)\r\n/\r\nsum by ($group_by) (\r\n    label_replace(\r\n        rate(\r\n          traefik_service_requests_total{service=~\"$namespace-.+\", service=~\"$service\"}\r\n      [$__rate_interval])\r\n    , \"namespace\", \"$1\", \"service\", \"^([a-z]+)-.+\")\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed (5xx) Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "req" } },
   "targets": [
    {
     "expr": "sum by ($group_by) (\r\n    label_replace(\r\n        increase(\r\n          traefik_service_requests_total{service=~\"$namespace-.+\", service=~\"$service\", code=~\"5..\"}\r\n      [$__rate_interval])\r\n    , \"namespace\", \"$1\", \"service\", \"^([a-z]+)-.+\")\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "3xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by ($group_by) (\r\n    label_replace(\r\n        rate(\r\n          traefik_service_requests_total{service=~\"$namespace-.+\", service=~\"$service\", code=~\"3..\"}\r\n      [$__rate_interval])\r\n    , \"namespace\", \"$1\", \"service\", \"^([a-z]+)-.+\")\r\n)\r\n/\r\nsum by ($group_by) (\r\n    label_replace(\r\n        rate(\r\n          traefik_service_requests_total{service=~\"$namespace-.+\", service=~\"$service\"}\r\n      [$__rate_interval])\r\n    , \"namespace\", \"$1\", \"service\", \"^([a-z]+)-.+\")\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "3xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "req" } },
   "targets": [
    {
     "expr": "sum by ($group_by) (\r\n    label_replace(\r\n        increase(\r\n          traefik_service_requests_total{service=~\"$namespace-.+\", service=~\"$service\", code=~\"3..\"}\r\n      [$__rate_interval])\r\n    , \"namespace\", \"$1\", \"service\", \"^([a-z]+)-.+\")\r\n)",
     "legendFormat": "{{ $group_by }} (3xx)"
    }
   ]
  },
  {
   "title": "4xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by ($group_by) (\r\n    label_replace(\r\n        rate(\r\n          traefik_service_requests_total{service=~\"$namespace-.+\", service=~\"$service\", code=~\"4..\"}\r\n      [$__rate_interval])\r\n    , \"namespace\", \"$1\", \"service\", \"^([a-z]+)-.+\")\r\n)\r\n/\r\nsum by ($group_by) (\r\n    label_replace(\r\n        rate(\r\n          traefik_service_requests_total{service=~\"$namespace-.+\", service=~\"$service\"}\r\n      [$__rate_interval])\r\n    , \"namespace\", \"$1\", \"service\", \"^([a-z]+)-.+\")\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "4xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "req" } },
   "targets": [
    {
     "expr": "sum by ($group_by) (\r\n    label_replace(\r\n        increase(\r\n          traefik_service_requests_total{service=~\"$namespace-.+\", service=~\"$service\", code=~\"4..\"}\r\n      [$__rate_interval])\r\n    , \"namespace\", \"$1\", \"service\", \"^([a-z]+)-.+\")\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Saturation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "Running Pods",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count by (namespace) (count by (pod, namespace) (container_last_seen{namespace=\"traefik\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HPA",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 77 },
   "targets": [
    {
     "expr": "avg by (namespace, horizontalpodautoscaler) (kube_horizontalpodautoscaler_status_current_replicas{namespace=\"traefik\"})",
     "legendFormat": "{{ namespace }}/{{ horizontalpodautoscaler }} (current)"
    },
    {
     "expr": "avg by (namespace, horizontalpodautoscaler) (kube_horizontalpodautoscaler_status_desired_replicas{namespace=\"traefik\"})",
     "legendFormat": "{{ namespace }}/{{ horizontalpodautoscaler }} (desired)"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"traefik\", image!=\"\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Working Set Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"traefik\", image!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Rx",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by (pod) (irate(container_network_receive_bytes_total{namespace=\"traefik\"}[$__rate_interval]) * 8)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Tx",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by (pod) (irate(container_network_transmit_bytes_total{namespace=\"traefik\"}[$__rate_interval]) * 8)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Size Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by ($group_by) (\r\n    label_replace(\r\n        rate(\r\n          traefik_service_requests_bytes_total{exported_service=~\"$namespace-.+\", exported_service=~\"$service\"}\r\n      [$__rate_interval])\r\n    , \"namespace\", \"$1\", \"exported_service\", \"^([a-z]+)-.+\")\r\n) * 8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Size Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by ($group_by) (\r\n    label_replace(\r\n        rate(\r\n          traefik_service_responses_bytes_total{exported_service=~\"$namespace-.+\", exported_service=~\"$service\"}\r\n      [$__rate_interval])\r\n    , \"namespace\", \"$1\", \"exported_service\", \"^([a-z]+)-.+\")\r\n) * 8",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}