apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
  labels:
    grafana_datasource: "1"

data:
  opencost.yaml: |
    apiVersion: 1
    datasources:
    - access: proxy
      name: zz-opencost
      type: prometheus
      url: http://vm-victoria-metrics-single-server.opencost.svc.cluster.local:8428
