server:
  resources:
    requests:
      memory: 50Mi
    limits:
      memory: 100Mi
  extraArgs:
    enableTCP6: "true"

  datasource:
    url: &url "http://vm-victoria-metrics-single-server.opencost.svc.cluster.local:8428"
  remote:
    write:
      url: *url
    read:
      url: *url

  config:
    alerts:
      groups:
        - name: total-cost
          interval: 1m
          rules:
            - record: sum_node_total_hourly_cost
              expr: >-
                sum(node_total_hourly_cost)
        - name: namespace-cost
          interval: 1m
          rules:
            - record: namespace_cpu_cost
              expr: >-
                sum by (namespace) (
                  sum by (namespace, instance) (container_cpu_allocation)
                  * on(instance) group_left() (avg by (instance) (node_cpu_hourly_cost))
                )
            - record: namespace_memory_cost
              expr: >-
                sum by (namespace) (
                  (
                    sum by (namespace, instance) (container_memory_allocation_bytes / 1024 / 1024 / 1024)
                    or sum by (namespace, instance) (container_memory_allocation_bytes) * 0
                  )
                  * on(instance) group_left() (avg by (instance) (node_ram_hourly_cost))
                )
