apiVersion: v1
kind: ServiceAccount
metadata:
  name: vlstorage-archive

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vlstorage-archive

rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vlstorage-archive

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vlstorage-archive
subjects:
  - kind: ServiceAccount
    name: vlstorage-archive
    namespace: victoria-logs
